version: "2"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
  flask:
    build:
      context: .
    command: sh -c "alembic upgrade head && python -m flask --app app.main run --host=0.0.0.0 --port=5000 --reload"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: on-failure

#alembic upgrade head &&